version: "3.6"
services:
  json-server:
    build:
      context: ./json-server
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
  mongo:
    image: 'mongo'
    volumes:
      - data:/data/db
    ports:
      - "666:27017"
  valyria:
    build:
      context: ../../valyria-node-ts
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: [ mongo,json-server ]

volumes:
  data: